---

- name: "Extract the backend files"
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: ~/

- name: "Start the app"
  shell: |
    cd ~/
    ls -al
    npm install
    pm2 stop default
    pm2 start npm -- start