---

- name: "Copy the artifact"
  copy:
    src: ~/project/artifact.tar.gz
    dest: ~/artifact.tar.gz
    backup: yes

- name: "Extract the backend files"
  shell: |
    tar xvfz ~/artifact.tar.gz

- name: "Start the app"
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start