---

- name: "Copies the artifact"
  copy:
    src: ~/project/artifact.tar.gz
    dest: ~/artifact.tar.gz
    backup: yes

- name: "Extracts the backend files"
  shell: |
    tar xvfz ~/artifact.tar.gz

- name: "Starts the app"
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start