- name: "install node exporter."
  become: yes
  shell: |
    sudo useradd --no-create-home node_exporter
    wget https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz
    tar xzf node_exporter-1.0.1.linux-amd64.tar.gz

- name: "install binary at /usr/local/bin"
  become: yes
  shell: |
    sudo cp node_exporter-1.0.1.linux-amd64/node_exporter /usr/local/bin/node_exporter
    rm -rf node_exporter-1.0.1.linux-amd64.tar.gz node_exporter-1.0.1.linux-amd64

- name: "configure node exporter service"
  become: yes
  copy:
    src: node_exporter.service
    dest: /etc/systemd/system/node-exporter.service

- name: "start node exporter service"
  become: yes
  shell: |
    sudo systemctl daemon-reload
    sudo systemctl enable node-exporter
    sudo systemctl start node-exporter